api/package.json
- add heroku-postinstall script to run lerna bootstrap
- fixes deployment issue
=> 🔧 add missing lerna bootstrap command

dashboard-app/src/Error.tsx
Adds padding back onto one of the `h3` elements. See https://github.com/TwinePlatform/twine-monolith/pull/30#discussion_r278665689
=> 🐛 fix mistaken padding refactor

api/Procfile, api/package.json
as discussed on slack
https://devcenter.heroku.com/articles/release-phase
=> 🔧 run migrations in release phase instead of postbuild

dashboard-app/src/auth/pages/Login/index.tsx
There's no register functionality, platform registrations are done manually via Edward, so add a `mailto` link instead!
=> 🚸 change (non-existent) register link to mailto

.travis/cc-report.sh
Need to augment the condition so that we always report coverage on builds triggered on `master`, so that we get the reports on code-climate.
=> 👷‍♀️ don't skip test coverage reporting on master

dashboard-app/src/navigation/Navbar/index.tsx, dashboard-app/src/navigation/pages.ts
Discovered as part of QA
* Use `react-router` provided path matching function to support path parameters
* Prevent the `matchPath` method from throwing (silent failure leading to empty navbar is probably less jarring for users, and therefore preferable.)
=> 🐛 fix navbar path matching on path patterns

dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts
- create ISO string format before creating moment/date object
fixes #105
=> 🐛 fix abbreviated month bug on firefox

dashboard-app/src/components/DataTable/index.tsx
**Issue:**
- onHeaderClick was being memoized with incorrect values due to `useCallback`
**Changes:**
- add headers to dep list so that a new callback is generated when this value changes
fixes #111
=> 🐛 fix sorting/rendering issue with tables

dashboard-app/src/dashboard/ByActivity/__tests__/index.test.ts, dashboard-app/src/dashboard/ByActivity/index.tsx, dashboard-app/src/dashboard/ByTime/__tests__/index.test.ts, dashboard-app/src/dashboard/ByTime/index.tsx, dashboard-app/src/dashboard/ByVolunteer/__tests__/index.test.ts, dashboard-app/src/dashboard/ByVolunteer/index.tsx
Fixes #128 
* `sortBy` state fragment tracks column index (`number`) instead of column name (`string`) since the latter is not fixed but the former is
* Use default empty initial state for `tableData` so components don't have to deal with the null case
* Render loader while data is being fetched to avoid rendering `NO DATA AVAILABLE` view unnecessarily
Note:
I think the hooks should be refactored to allow this all to happen a little more easily and with quite so much boilerplate. We can certainly build some higher-level hooks on top of the ones we already have. However I decided not to do this in this PR in the interests of getting things through QA more quickly. I think we should do it this sprint though.
=> 🐛 fix bug by tracking sorted column by index instead of title

dashboard-app/src/components/Tabs/Tab.tsx, dashboard-app/src/components/Tabs/TabGroup.tsx, dashboard-app/src/components/Tabs/TabList.tsx, dashboard-app/src/components/Tabs/TabListItem.tsx, dashboard-app/src/components/Tabs/__tests__/TabGroup.test.tsx, dashboard-app/src/components/Tabs/index.tsx
Fixes #121 
* Add `TabGroup` component (and sub-components)	based on designs
* Add tests
Usage example:
```
<TabGroup titles={[TABLE_TITLE, 'Some other table']}>
<DataTable
{...tableData}
title={TABLE_TITLE}
sortBy={sortBy}
initialOrder="desc"
onChangeSortBy={onChangeSortBy}
showTotals
/>
<DataTable
{...tableData}
title={"Some other table"}
sortBy={sortBy}
initialOrder="desc"
onChangeSortBy={onChangeSortBy}
showTotals
/>
</TabGroup>
```
=> ✨ add tab components

api/src/models/visitor.ts, lib/twine-util/__tests__/promises.test.ts, lib/twine-util/promises.ts
Related to #136
Related to #123 
Only merge this if #136 proves insufficient in resolving #123
=> 🐛 limit concurrent queries by replacing Promise.all with Promises.series

dashboard-app/src/components/Errors.tsx, dashboard-app/src/components/StackedBarChart/index.tsx, dashboard-app/src/dashboard/ByActivity/index.tsx, dashboard-app/src/dashboard/ByTime/index.tsx, dashboard-app/src/dashboard/ByVolunteer/index.tsx, dashboard-app/src/dashboard/hooks/useAggregateDataByActivity.ts, dashboard-app/src/dashboard/hooks/useAggregateDataByTime.ts, dashboard-app/src/dashboard/hooks/useAggregateDataByVolunteer.ts, dashboard-app/src/util/months.ts
Related to #130 
* Append active date filter to chart and table titles on Volunteer and Time pages (not specified on Activity page, plus date is a different format)
* ~~Add "NO DATA AVAILABLE" view to chart~~ **REMOVED TO AVOID CONFLICTS WITH @astroash**
* Minor formatting and type tidying
I think we should do the following, and can either include them in this PR, or make issues and we can work on them afterwards:
1. More unified interface for `AggregatedData` related things
* Single `AggregatedData` namespace exposed via `index.ts` file
* `AggregatedData.fromLogs()`, `AggregatedData.toTableData()`, `AggregatedData.empty()`, `AggregatedData.AggregatedData` (type) etc.
2. Any reason that graph data is computed inside the `<X>Tabs.tsx` component but `TableData` is computed and stored in the …
=> 🐛 Minor fixes for dashboard charts

dashboard-app/src/components/StackedBarChart/Chart.tsx, dashboard-app/src/components/StackedBarChart/RoundedBar/Rectangles.ts, dashboard-app/src/components/StackedBarChart/RoundedBar/RoundedBarChart.ts, dashboard-app/src/components/StackedBarChart/RoundedBar/__tests__/Rectangles.test.ts, dashboard-app/src/components/StackedBarChart/RoundedBar/__tests__/RoundedBarChart.test.ts, dashboard-app/src/components/StackedBarChart/RoundedBar/index.tsx, dashboard-app/src/components/StackedBarChart/index.tsx, dashboard-app/src/components/StackedBarChart/utils/chartjsUtils.ts, dashboard-app/src/dashboard/ByTime/__tests__/index.test.ts, dashboard-app/src/dashboard/ByVolunteer/__tests__/index.test.ts, dashboard-app/src/dashboard/dataManipulation/aggregatedToGraphData.ts
Related to #130 
Found that the code actually admitted quite a bit of re-organisation, and that a _lot_ more of it was dead code than we thought!
* Create types for basic concepts required for drawing calculations
* Separate side-effects (drawing) from pure stuff (calculating parameters for drawing)
* Make rounding work with native legend (by inspecting hidden) as well as with custom legend (by relying on 0-values)
* `RoundedBarChart` exports a mutating function so its parent can control when the mutation occurs.
=> 💄 Add bar chart with rounded tops

dashboard-app/src/components/StackedBarChart/index.tsx, dashboard-app/src/components/StackedBarChart/utils/__tests__/index.test.ts, dashboard-app/src/components/StackedBarChart/utils/util.ts, dashboard-app/src/dashboard/ByTime/TimeTabs.tsx, dashboard-app/src/dashboard/ByTime/index.tsx, dashboard-app/src/dashboard/ByVolunteer/VolunteerTabs.tsx, dashboard-app/src/dashboard/ByVolunteer/index.tsx, dashboard-app/src/dashboard/hooks/useAggregateDataByTime.ts, dashboard-app/src/dashboard/hooks/useAggregateDataByVolunteer.ts
**Changes:**
- legend data can be created from rows as it contains `id` & `name` values. Creating this data from requests (of activities or volunteers) causes discrepancies as soft deleted data is not present. 
fixes #157
=> 🐛 fix legend data creation

dashboard-app/src/dashboard/dataManipulation/__tests__/aggregatedToGraphData.test.ts, dashboard-app/src/dashboard/dataManipulation/aggregatedToGraphData.ts
**Changes**
- display colours in the same order as legend
fixes #171
=> 📊 reverse order of stack in stacked bar chart

api/database/index.ts, api/package-lock.json, api/package.json, api/src/api/v1/community_businesses/__tests__/volunteer_logs.test.integration.ts, api/src/api/v1/community_businesses/volunteer_logs.ts
fixes #61 
Just add a role check if `userId === 'me'`, allowing only `VOLUNTEER` and `VOLUNTEER_ADMIN` users.
=> 🐛 disallow CB_ADMIN from adding own logs

api/package-lock.json, api/package.json, api/src/api/v1/users/__tests__/login.test.integration.ts, api/src/api/v1/users/login.ts
Moving the role check before the payload check prevents this error.
Fixes #88
=> 🐛 prevent 500 error on login when user has no password

api/package-lock.json, api/package.json, dashboard-app/src/features/dashboard/ByActivity/__tests__/index.test.ts, dashboard-app/src/features/dashboard/ByActivity/index.tsx, dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts, dashboard-app/src/features/dashboard/ByTime/index.tsx, dashboard-app/src/features/dashboard/ByVolunteer/__tests__/index.test.ts, dashboard-app/src/features/dashboard/ByVolunteer/index.tsx, dashboard-app/src/features/dashboard/components/DataTable/index.tsx, dashboard-app/src/features/dashboard/components/DataTable/types.ts
related to #98 
Allow `onChangeSortBy` to return default sort order.
=> 🔬 allow onChangeSortBy to return default sort order to address QA defect

api/package-lock.json, api/package.json, api/src/models/community_business.ts, api/src/models/user.ts, api/src/models/volunteer_log.ts, dashboard-app/src/features/dashboard/ByActivity/index.tsx, dashboard-app/src/features/dashboard/ByTime/index.tsx, dashboard-app/src/features/dashboard/ByVolunteer/index.tsx, dashboard-app/src/features/dashboard/dataManipulation/__tests__/downloadCsv.test.ts, dashboard-app/src/features/dashboard/dataManipulation/aggregatedToCsv.ts, dashboard-app/src/features/dashboard/dataManipulation/downloadCsv.ts, dashboard-app/src/features/dashboard/dataManipulation/logsToAggregatedData.ts, dashboard-app/src/features/dashboard/dataManipulation/util.ts, lib/twine-util/arrays.ts, lib/twine-util/objects.ts
fixes #98 
- CSV sorting matches (initial) table sorting. 
- Specifically, if user has changed the initial order from 'asc' -> 'desc' or vice-versa, it doesn't reflect this change.
- `downloadCsv` throws errors now -- reducing its responsibility
- Download errors are now managed in the top-level component.
- Improve type inference in `dataManipulation/util` and `twine-util`.
=> ↕ CSV sorting

api/reporting/reports/volunteer_logs_raw.ts
Grabbing only volunteers in the raw dump means "creator" information in cases where CB_ADMIN users are creating logs on behalf of VOLUNTEER users is left blank.
The data dump in GDrive has already been updated with this change.
**Testing Requirements:** None
=> 📜 reporting: grab users instead of only volunteers

dashboard-app/src/features/dashboard/Dashboard/__tests__/useDashboardStatistics.test.ts, dashboard-app/src/features/dashboard/Dashboard/__tests__/util.test.ts, dashboard-app/src/features/dashboard/Dashboard/useDashboardStatistics.ts, dashboard-app/src/features/dashboard/Dashboard/util.ts, dashboard-app/src/features/dashboard/components/DataCard/index.tsx, dashboard-app/src/features/dashboard/components/DataCard/types.ts, lib/twine-util/__tests__/arrays.test.ts, lib/twine-util/__tests__/string.test.ts, lib/twine-util/arrays.ts, lib/twine-util/string.ts
Fixes #236
Moved the truncation logic inside `DataCard` (mediated by props) because it handles the bolding internally. Alternatively we could make `DataCard` accept render props and move the logic outside, but this seems more complicated than necessary. The other alternative is to add more of the application logic inside the `DataCard` but this seems like a bad idea if we're trying to keep it as dumb as possible.
- Add tests on `*StatsToProps` functions
- Modify `String.listify` to accept flag telling it not to insert `"and"` in the list -- defaults to the pre-existing behaviour
- Add another util to handle truncation
- `alternateBold` accepts an `offset` argument to avoid having to prepend an empty string to the argument sometimes
- Statistics functions now pass _all_ top values to the …
=> 🐛 fix dashboard tile truncation logic

api/database/index.ts, api/database/migrations/20190801_track_visitor_sign_in_type.ts, api/database/migrations/sql/20190801_track_visitor_sign_in_type.sql, api/src/api/v1/community_businesses/__tests__/visit_logs.test.integration.ts, api/src/api/v1/community_businesses/temporary/__tests__/delete.test.integration.ts, api/src/api/v1/community_businesses/visit_logs.ts, api/src/models/__tests__/community_business.test.integration.ts, api/src/models/community_business.ts, api/src/models/types.ts, visitor-app/src/api/index.js, visitor-app/src/visitors/pages/SignIn/SignInForm.js, visitor-app/src/visitors/pages/SignIn/index.js
**NOTE:** Dates for migration may need editing depending on whether this PR or #227 goes in first
fixes #226
- create table to track visitor sign in type
- visitor app req specifies sign in type
- store sign in type to db
- log in visitor with QR code
- log in visitor with sign in with name
- manually check db is updates (optional)
- no restrictions. 
- deploy when ready.
=> 👀 monitor visitor sign in type

api/config/config.development.ts
- remove space in default redis url
=> 🐛 fix default redis url for dev env

api/config/__tests__/index.test.ts, api/config/config.defaults.ts, api/config/config.schema.ts, api/config/types.ts, api/docs/configuration.md, api/src/api/v1/auth.ts, api/src/auth/index.ts, api/src/auth/strategies/heroku_webhook/index.ts, api/src/server.ts, api/src/services/email/dispatcher.ts, api/src/services/email/index.ts, api/src/services/email/templates.ts, api/src/webhooks/v1/heroku/index.ts, api/src/webhooks/v1/heroku/onStagingRelease.ts, api/src/webhooks/v1/index.ts
relates #238 
- add heroku strategy for authentication
- add webhook endpoint sending devs emails
- add devs emails to env var
- add template id for postmark
- NOTE: not tested as this is a dev facing action. Can test if wanted
- not user facing test in production
- no release restrictions, deploy when ready
=> 🕸 add webhook endpoint for heroku releases

dashboard-app/src/features/dashboard/ByTime/TimeTabs.tsx, dashboard-app/src/features/dashboard/ByVolunteer/VolunteerTabs.tsx, dashboard-app/src/features/dashboard/components/StackedBarChart/Chart.tsx, dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx, dashboard-app/src/features/dashboard/components/StackedBarChart/utils/__tests__/index.test.ts, dashboard-app/src/features/dashboard/components/StackedBarChart/utils/util.ts
fixes #239 
- selection of legend items is configurable
- Add text overlay when legend items are disabled
- Login
- Navigate to "/time"
- Expect all legend items to be de-selected
- Expect to see message "Select an activity to show data"
- Expect chart not to be displayed
- Select any number of activities from the legend
- Expect chart to be displayed
- Expect previously displayed message to disappear
- Navigate to "/volunteers"
- Expect all legend items to be de-selected
- Expect to see message "Select a volunteer to show their hours"
- Expect chart not to be displayed
- Select any number of volunteers from the legend
- Expect chart to be displayed
- Expect previously displayed message to disappear
- review by PO then release, no comms
=> 🚸 add overlay to graph page when no legend items selected

.travis.yml, .travis/cc-download.sh, .travis/cc-report.sh
fixes #276
- Use absolute paths using `dirname` function instead of relying on `.`
- Check that code-coverage reports have been uploaded
N/A
N/A
=> 🔧 travis/code-climate fix

.travis.yml, api/package.json
20 minute builds is a bit too long
- Parallelise integration tests; they use transactions, so all database changes are isolated
- Only use one build stage
N/A
N/A
N/A
=> 🔧 parallelise tests and only use one build stage

api/src/api/v1/community_businesses/temporary/__tests__/delete.test.integration.ts, api/src/api/v1/community_businesses/visitors/__tests__/get.test.integration.ts, api/src/api/v1/community_businesses/visitors/__tests__/put.test.integration.ts, api/src/api/v1/users/__tests__/put.test.integration.ts, api/src/api/v1/users/__tests__/roles.test.integration.ts, api/src/api/v1/users/__tests__/schema.test.unit.ts, api/src/api/v1/users/register/__tests__/visitors.test.integration.ts, api/src/api/v1/users/register/visitors.ts, api/src/api/v1/users/schema.ts, visitor-app/src/api/index.js, visitor-app/src/visitors/index.js, visitor-app/src/visitors/pages/SignUp/index.js, visitor-app/src/visitors/pages/SignUp/signup_form.js, visitor-app/src/visitors/pages/__tests__/Signup.test.js
relates https://github.com/TwinePlatform/twine-visitor/issues/643
- add postcode validation with tests
- set post code as required for visitor registration
- add postcode field to visitor sign up on visitor app
- fix error messages for phone number as this wasn't displaying
- minor visitor app file rearranging
- try to sign up without a postcode = ⁉️ validation error message
- try to sign up with an postcode > 10 characters = ⁉️ validation error message
- try to sign up with an invalid postcode format eg all numbers or all letters = ⁉️ validation error message
- minor (Devs to release); validation required on postcode
- Visitor App
- API
=> 🔍 add required postcode for visitors registration

api/database/migrations/20190808_create_monitoring_for_ignoring_synced_logs.ts, api/database/migrations/sql/20190808_create_monitoring_for_ignoring_synced_logs.sql, api/src/api/v1/community_businesses/__tests__/volunteer_logs.test.integration.ts, api/src/api/v1/community_businesses/volunteer_logs.ts, api/src/auth/scopes/__tests__/index.test.ts, api/src/auth/scopes/index.ts, api/src/models/types.ts, api/src/models/volunteer_log.ts, lib/twine-util/__tests__/promises.test.ts, lib/twine-util/promises.ts, volunteer-app/www/js/app.js
related to #246 
- Mainly an attempt to prevent this endpoint from returning non-200 status codes where reasonable to avoid users of the volunteer app being trapped in offline mode ☹️
- re-implement the temporary fix in #245 
- allow logs with invalid timestamps for `startedAt` and `deletedAt` through validation but ignore them when actually syncing
- Remove sync operation from transaction: if only some logs can be synced, they should be, others ignored
- Endpoint responds with `{ synced: Number, ignored: Number }` to avoid transaction problems in tests
- Ignored logs are stored as JSON blobs in temporary table `invalid_synced_logs_monitoring`.
- Add some `Scopes` utility functions (with a little added validation)
- Add a `Promises.some` utility function: like `Promise.all` but resolves …
=> 🚑 ignore invalid date-strings from synced logs

volunteer-app/www/js/app.js
related to #259 #246 
- Ensure `userId` is specified in sync payload if available
- Complicated by inconsistent use of snake and camel case 😔
- Fallback to `startedAt` if `date_of_log` unavailable
- Online mode
- Create log as `VOLUNTEER`
- Check DB records user ID accurately
- Create log as `VOLUNTEER_ADMIN`
- Check DB records user ID accurately
- Create log for `VOLUNTEER` as `VOLUNTEER_ADMIN`
- Check DB records user ID accurately
- Offline mode
- Enter offline mode on "view logs" screen
- Repeat steps above, syncing logs after each step.
- Bundled with other volunteer app changes
- Volunteer app
=> 🐛 fix userId bug in volunteer app sync

api/package-lock.json, api/package.json, api/tslint.json
Fixes issue with tslint suddenly deciding to lint types differently
Since tslint is deprecated anyway, we should switch over to eslint (see #32)
- copy over linting config from `tslint-config-twine` to api as a quick fix
N/A 
N/A
N/A
=> 🙄 copy over linting config to api as a quick fix

dashboard-app/src/features/dashboard/components/StackedBarChart/Chart.tsx, dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx, dashboard-app/src/features/dashboard/dataManipulation/logsToAggregatedData.ts
Found this stuff in the course of working on #32 but thought it should be split out.
- Display overlay when `data` is empty
- Rename `noActiveLegendText` to `overlayText` since it is also triggered when there's no data in the selected range.
- Fix bug found in `logsToAggregatedData` where an empty range sometimes causes a crash
- Go to `/time` or `/volunteer`
- Select a date range with no data
- Observe overlay message
- Minor change, release when ready
- Dashboard
=> 🚸 display overlay when no data in range

api/src/api/v1/schema/request.ts, api/src/api/v1/types.ts, api/src/models/community_business.ts, api/src/models/organisation.ts, api/src/models/types.ts, api/src/models/user.ts, api/src/models/visitor.ts, api/src/models/volunteer_log.ts, api/src/types/internal.ts
- Replace custom `Map` type with Typescript `Record` type
- Replace custom `Omit` type with Typescript `Omit` type
- Define `Dictionary` using `Record`
N/A
N/A
N/A
=> 🗜 use Typescript provided Record, Omit types

api/bin/api_token.ts, api/src/auth/schema/session_cookie/index.ts
- Fix `api_token` script so it actually prints the API token
- Call `Boom` in the special way that we need to in order to ensure other schema are also checked.
- Create an API token for a CB using the script
- Use the API token to send a request to an open endpoint (e.g. cb/me/visitors)
- When ready
- API
=> 🐛 fix external API access issues

dashboard-app/src/features/dashboard/components/StackedBarChart/Chart.tsx
fixes #340 
- The text overlay broke the on-hover -- use `z-index` to fix it
- Hover over charts -- see if tooltips appear
Release when ready
- Dashboard
=> 🐛 fix on-hover bug

api/src/api/v1/community_businesses/volunteers/__tests__/projects.test.integration.ts, api/src/models/volunteer_log.ts
Found during work on #325 
- Use transaction in projects test to isolate effects of each test
- As a result, one test fails: changing casing of project impossible because of name conflict check
- Exclude log being updated from conflict check
- N/A
- When ready
- API
=> 🐛 fix bug in projects tests and updateProject method

visitor-app/package-lock.json, visitor-app/package.json, visitor-app/src/__tests__/util.test.js, visitor-app/src/cb_admin/pages/VisitsData/__tests__/dateRange.test.js, visitor-app/src/cb_admin/pages/VisitsData/dateRange.js, visitor-app/src/shared/__tests__/constants.test.js, visitor-app/src/shared/constants.js, visitor-app/src/util.js
- Add `DateRanges` utility module to deal with the date ranges relevant for the visits charts
- Add several utility functions used for data processing of api results for the visits charts (used in subsequent PRs)
N/A
N/A
N/A
=> ✨ visitor charts utilities

api/src/api/v1/community_businesses/__tests__/visit_logs.test.integration.ts, api/src/api/v1/community_businesses/visit_logs.ts, api/src/api/v1/community_businesses/visit_logs_aggregates.ts, api/src/api/v1/community_businesses/volunteer_logs.ts, api/src/api/v1/schema/request.ts, api/src/api/v1/types/api.ts, api/src/api/v1/user_logs/visit_logs.ts, api/src/api/v1/user_logs/volunteer_logs.ts, api/src/api/v1/users/schema.ts, api/src/models/__tests__/visitor.test.integration.ts, api/src/models/community_business.ts, api/src/models/types.ts, api/src/models/visitor.ts
- Allow `since` and `until` query params on `GET /community-businesses/me/visit-logs`
- Update models: Visit events now include their category
Manual testing done on later PRs with client-side changes
N/A - wait for later PRs
API
=> ♻️ modify visit-logs api to allow time filtering

visitor-app/src/cb_admin/pages/VisitsData/__tests__/data.test.js, visitor-app/src/cb_admin/pages/VisitsData/__tests__/util.test.js, visitor-app/src/cb_admin/pages/VisitsData/data.js, visitor-app/src/cb_admin/pages/VisitsData/util.js
- Adds data processing functions
N/A (test together with final PR)
N/A
N/A
- In `preProcessVisitors`, the step of using `combineValues` to collect values of `visitActivity`, `createdAt`, and `category` onto the visitor object was an attempt to make the calculation of stats slightly simpler (i.e. to avoid having to iterate through the `visits` array in each `VisitorStats` function). However, it may be that this just obfuscates what's happening more than necessary (and iterating through visits won't be much slower). LMK what you think and I can get rid of this bit.
=> ✨ data processing and utilities for visits charts

dashboard-app/src/features/dashboard/dataManipulation/__tests__/util.test.ts, dashboard-app/src/features/dashboard/dataManipulation/aggregatedToCsv.ts, dashboard-app/src/features/dashboard/dataManipulation/aggregatedToTableData.ts, dashboard-app/src/features/dashboard/dataManipulation/logsToAggregatedData.ts, dashboard-app/src/features/dashboard/dataManipulation/tableType.ts, dashboard-app/src/features/dashboard/dataManipulation/util.ts
Changes made as part of adding projects chart (see #335)
- Use `collectBy` to simplify `logsToAggregateData`
- Rename `abbreviateDateString` fns to `formatDateString`, since the format is an argument
- Chronologically sort column headers in CSV export
- Support projects in `getIdAndName`
- Check charts, tables and CSVs on each page
- Not yet.
- B/A
=> ♻️ Refactor dashboard logs manipulation code

dashboard-app/src/features/dashboard/Dashboard/__tests__/index.test.ts, dashboard-app/src/features/dashboard/Dashboard/__tests__/useDashboardStatistics.test.ts, dashboard-app/src/features/dashboard/Dashboard/__tests__/util.test.ts, dashboard-app/src/features/dashboard/Dashboard/index.tsx, dashboard-app/src/features/dashboard/Dashboard/useDashboardStatistics.ts, lib/twine-util/package.json, lib/twine-util/tsconfig.json, lib/twine-util/tsconfig.production.json
related to #335
- Add projects stats to tile on dashboard landing page
- Log in as account with logs in the past month -- see stats showing most popular project
- Log in as account with no logs in the past month -- see "no data available"
- On PO approval, with the rest of the projects changes
- Dashboard
=> ✨ add projects stats to dashboard

api/docs/public_api.md, api/src/api/v1/users/visitors/__tests__/search.test.integration.ts, api/src/api/v1/users/visitors/search.ts
fixes #384 
- Expose `POST /v1/users/visitors/search` endpoint to external users via `external` auth strategy
- Update public API docs
- Send valid QR code hash to endpoint using API token (expect visitor object)
- Send invalid QR code hash to endpoint using API token (expect null)
- Anytime
- API
=> 🔎 expose visitor search endpoint

dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx, dashboard-app/src/features/dashboard/dataManipulation/logsToAggregatedData.ts, dashboard-app/src/features/dashboard/dataManipulation/tableType.ts
- Make `groupByX` and `groupByY` types narrower
- Expand the cases considered when inferring overlay text from `groupByX` value
- Deselect all legend values on all pages (expect message to be appropriate to data that would be displayed)
- With rest of feature branch
- Dashboard
=> 🐛 fix no data overlay text on dashboard

api/database/migrations/20200106_new_gender_options.ts, api/database/migrations/sql/20200106_new_gender_options.sql, api/src/api/v1/schema/request.ts
related to #409 
- Adds items detailed in #409 to list of permitted gender options for API payloads
- Send `POST /v1/users/register/visitors` with one of the new gender options
- Expect 200
- When ready, no PO approval required
- API
- After deployment, add new gender options to the database with:
```sql
insert into gender (gender_name) values ('non-binary'), ('intersex'), ('other');
```
=> 🧩 expand gender options in validation schema
