TwinePlatform/twine-monolith

- api/src/api/v1/users/register/__tests__/visitors.test.integration.ts
- api/src/api/v1/users/register/visitors.ts
- add check in register
- add tests
TwinePlatform/twine-visitor#707
> 🐛 vol_admin cannot have two roles

- visitor-app/src/confirm_role/pages/ConfirmRole.js
- visitor-app/src/shared/components/form/base.js
bug found in https://github.com/TwinePlatform/twine-visitor/issues/707
> 🐛 fix confirm role redirect

- dashboard-app/package-lock.json
- dashboard-app/package.json
- known bug with styled-component types that slows down compile time
> ⬇️ fix typescript compile time

- dashboard-app/src/App.tsx
- dashboard-app/src/api/index.ts
- dashboard-app/src/components/Navbar/Navigation.tsx
- dashboard-app/src/components/Navbar/index.tsx
- dashboard-app/src/dashboard/ByActivity.tsx
- dashboard-app/src/dashboard/ByTime.tsx
- dashboard-app/src/dashboard/ByVolunteer.tsx
- dashboard-app/src/dashboard/__tests__/ByActivity.test.ts
- dashboard-app/src/dashboard/__tests__/ByTime.test.ts
- dashboard-app/src/dashboard/__tests__/ByVolunteer.test.ts
- add pages to routing
- pages call relevant data
- basic title tests
- navbar shows active page
fixes #25
> ✨ setup pages for new dashboard

- dashboard-app/src/Error.tsx
- dashboard-app/src/components/Buttons.tsx
- change copy based on params
- add default styling to buttons
fixes #29
NOTE: briefly looked into testing but it is complicated as the component relies on url params. As this component is not vital business logic it doesn't seem worth spending time on.
> ✨ add Error Page

- dashboard-app/package.json
- temp-admin-dashboard-app/package.json
- 3000 visitor
- 3100 dashboard
- 3200 twine-admin
> 🔧 react apps run on different local 3000 ports

- api/config/__tests__/index.test.ts
- api/config/config.defaults.ts
- api/config/config.development.ts
- add new localhost ports to cors whitelisting
> 🐛 add localhost ports to whitelist

- api/tsconfig.json
- lib/twine-util/package.json
- lib/twine-util/tsconfig.json
> 🔧 compile local modules postinstall

- dashboard-app/src/components/Card.tsx
- dashboard-app/src/components/DataTable/DataTableCell.tsx
- dashboard-app/src/components/DataTable/DataTableHeaderRow.tsx
- dashboard-app/src/components/DataTable/index.tsx
- dashboard-app/src/components/DatePicker/index.tsx
- dashboard-app/src/components/Label.tsx
- dashboard-app/src/components/Toggle.tsx
- dashboard-app/src/components/UnitToggle.tsx
- dashboard-app/src/components/UtilityBar.tsx
Related to #39
* Styling fixes to `DataTable` component
* Add `Toggle` and `UnitToggle` button components
* Add `UtilityBar` component
> ✨ Add utility bar

- api/package.json
- api/tsconfig.json
This was missed in the move to a monorepo
> 👷‍♀️ Add server checks to Travis build

- .travis.yml
- .travis/cc-download.sh
- .travis/cc-report.sh
Fixes #1 
Add initial setup for codecov
> 📈 Codeclimate

- dashboard-app/src/styles/index.css
Lock horizontal scrolling on app.
> 💄 fix horizontal scrolling issue

- dashboard-app/src/navigation/__tests__/pages.test.ts
- dashboard-app/src/navigation/pages.ts
> 🐛 add tests on dashboard navigation bug

- dashboard-app/src/components/DataTable/DataTableHeaderRow.tsx
- dashboard-app/src/components/DataTable/__tests__/index.test.tsx
- dashboard-app/src/components/DataTable/index.tsx
- dashboard-app/src/components/DatePicker/styles.css
Fixes #61 
Fixes #77 
* Add a no-data view for tables (instead of just an empty table)
* Make table columns fixed-width
* Minor fix to date-picker arrow alignment
> 🐛 fixed width table & add no data view

- dashboard-app/src/util/__tests__/months.test.ts
- dashboard-app/src/util/months.ts
- default date values set to beginning of month
- fixes #75
> 🐛 fix default date values

- dashboard-app/src/components/DataTable/DataTableTotalsRow.tsx
- dashboard-app/src/components/DataTable/__tests__/index.test.tsx
- dashboard-app/src/components/DataTable/index.tsx
- dashboard-app/src/components/DataTable/types.ts
- dashboard-app/src/components/DataTable/util.ts
- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
> ✨ add totals row to data table

- dashboard-app/src/components/DatePicker/Selector.tsx
- dashboard-app/src/components/Toggle.tsx
> 💄 give clickable elements cursor:pointer

- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/hooks/useAggDataOnRes.ts
- dashboard-app/src/util/__tests__/months.test.ts
- dashboard-app/src/util/dataManipulation/__tests__/aggregateToTableData.test.ts
- dashboard-app/src/util/dataManipulation/__tests__/logsToAggregatedData.test.ts
- dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts
- dashboard-app/src/util/dataManipulation/downloadCsv.ts
- dashboard-app/src/util/dataManipulation/tableType.ts
- dashboard-app/src/util/months.ts
**Changes:**
- separate formatting of months.
- agg data is verbose format eg June 2018
- table data is abbreviated format eg Jun 18
fixes #81
> ✨ abbreviate months

- dashboard-app/src/components/Buttons.tsx
- dashboard-app/src/components/Headings.tsx
- dashboard-app/src/components/Toggle.tsx
- dashboard-app/src/index.tsx
- dashboard-app/src/navigation/Navbar/Link.tsx
- dashboard-app/src/navigation/Navbar/index.tsx
- dashboard-app/src/styles/design_system/fonts.ts
- dashboard-app/src/styles/design_system/index.ts
- dashboard-app/src/styles/design_system/media_queries.ts
- dashboard-app/src/styles/index.css
**Changes:**
- root font size set by media queries
- make heading weight light
- add responsive spacing to navbar
relates #95 
I would like to get these changes deployed to staging to get further feedback on design
> 𝒜 amend font sizes

- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/util/dataManipulation/__tests__/logsToAggregatedData.test.ts
- dashboard-app/src/util/dataManipulation/logsToAggregatedData.ts
- deleted -> deleted user
- update table names
fixes #87
> 🖋 amend copy

- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/util/dataManipulation/aggregatedToTableData.ts
* Add `sortBy` to arguments of `aggregatedToTableData` so each table can specify initial sort column
> 🐛 Match initial sorting with user stories

- dashboard-app/src/dashboard/ByActivity/datePickerConstraints.ts
- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/datePickerConstraints.ts
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/util/__tests__/months.test.ts
- dashboard-app/src/util/months.ts
**Changes:**
- get defaults for toDate/fromDate from datePickerConstraints
- remove default to/from dates from Months model
relates #118
> 🐛 fix default dates on Activity Page

- dashboard-app/src/navigation/Navbar/index.tsx
- dashboard-app/src/navigation/__tests__/pages.test.ts
- dashboard-app/src/navigation/pages.ts
> 🐛 fix nav-bar page order

- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
- render utility bar when waiting for data as unmounting was causing state errors
fixes #131
> 🐛 quick fix date-picker bug

- api/config/config.production.ts
- api/config/util.ts
related to #123
when this is merged I'll change the env var value as described in my comment in #123 and see if that helps things, otherwise we'll go to option 2.
> 🔧 make pool limit configurable via env var

- api/reporting/reports/cb_engagement/index.ts
This is just a dev convenience to avoid having to run ~8 commands every few weeks.
> 📜 add single file to run all CBE reports

- dashboard-app/src/components/Tabs/TabGroup.tsx
- dashboard-app/src/components/UtilityBar.tsx
- dashboard-app/src/dashboard/ByActivity/index.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
**Changes:**
- remove unnecessary overrides
- add margin to bottom
fixes #151
> 💅 fix styling of util bar

- .heroku/config.sh
Adds script to pull and push config variables to and from heroku apps. Simple utility I used when creating the most recent dashboard clone app. Requires heroku CLI to be installed and already authenticated.
> 📜 add heroku config script

- dashboard-app/src/auth/pages/Login/index.tsx
fixes #89 
center the snackbar and stick it above the footer
> 💄 fix notification bar layout

- dashboard-app/src/components/DataTable/index.tsx
- dashboard-app/src/components/StackedBarChart/Chart.tsx
- dashboard-app/src/components/StackedBarChart/Legend/index.tsx
- dashboard-app/src/components/StackedBarChart/index.tsx
- dashboard-app/src/dashboard/ByTime/TimeTabs.tsx
* Add no-data view to chart
* Make title layout consistent between chart/table view
* Code formatting
> ✨ add no data view to dashboard charts

- dashboard-app/src/components/DataTable/index.tsx
- dashboard-app/src/components/FullWidthTextBox.tsx
- dashboard-app/src/components/StackedBarChart/Chart.tsx
- dashboard-app/src/components/StackedBarChart/index.tsx
**Changes:**
- refactor display messages to use FullWidthTextBox
- render different messages dependent on page
fixes #161
> 📊 display message on deselect of all legend items

- dashboard-app/src/components/Errors.tsx
- dashboard-app/src/dashboard/dataManipulation/__tests__/downloadCsv.test.ts
- dashboard-app/src/dashboard/dataManipulation/aggregatedToCsv.ts
- dashboard-app/src/dashboard/dataManipulation/downloadCsv.ts
- dashboard-app/src/dashboard/dataManipulation/logsToAggregatedData.ts
- Check if download failed before data is empty, and display message if so
- Add test on this case
Fixes #178
> 🐛 Add specifc CSV error msg when data is empty

- dashboard-app/src/components/StackedBarChart/Chart.tsx
- dashboard-app/src/components/StackedBarChart/RoundedBar/index.tsx
- dashboard-app/src/components/StackedBarChart/RoundedBar/tooltipCenter.ts
- dashboard-app/src/components/StackedBarChart/index.tsx
- dashboard-app/src/components/StackedBarChart/utils/chartjsUtils.ts
- dashboard-app/src/styles/design_system/colours.ts
**Changes:**
- change colour to match designs
- position in center of bar
- set title of tt to total with unit (hrs/days)
- set description of tt to categeorgy w/o total
fixes #166
> 📊 customise tooltip

- dashboard-app/src/components/StackedBarChart/index.tsx
- dashboard-app/src/dashboard/ByTime/TimeTabs.tsx
- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/VolunteerTabs.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
**Changes:**
- legend state held on page level to allow for persistence on tab switching
relates #163
> ♻️ move legend state to page component

- dashboard-app/src/dashboard/ByTime/index.tsx
- dashboard-app/src/dashboard/ByVolunteer/index.tsx
> 🐛 Fix csv filenames

- dashboard-app/src/components/UtilityBar.tsx
> 👆🏽 rename download button

- dashboard-app/package-lock.json
- dashboard-app/package.json
- dashboard-app/src/components/UtilityBar.tsx
fixes #162 
Dodgy logic in dependency 🙄
> ⬆️ upgrade date-picker to fix bug

- dashboard-app/src/components/Tabs/TabList.tsx
- dashboard-app/src/components/Tabs/TabListItem.tsx
Fixes #172 
Fixes #173 
* Increase border width of selected tab
* Darken colour of `TabList` border bottom
* Increase horizontal padding of tab elements
> 💅 improve TabGroup styling

- dashboard-app/src/components/DatePicker/Selector.tsx
- dashboard-app/src/components/Headings.tsx
- dashboard-app/src/components/StackedBarChart/Legend/LegendItem.tsx
- dashboard-app/src/components/StackedBarChart/Legend/index.tsx
- dashboard-app/src/navigation/Navbar/index.tsx
- dashboard-app/src/styles/design_system/media_queries.ts
- dashboard-app/src/styles/index.css
**Changes:**
- change media queries to be Desktop First
- resize fonts below large desktop
- change default sizing
- add font size to date picker
- make legend fontsize smaller
fixes #103 
relates  #168
> 𝒜 resize fonts n padding

- dashboard-app/package-lock.json
- dashboard-app/package.json
- dashboard-app/src/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/dashboard/ByVolunteer/__tests__/index.test.ts
> ✅ fix test by using mockdate

- api/package-lock.json
- api/package.json
> ⬆️ upgrade ramda types

- dashboard-app/src/features/dashboard/components/Polaroid.tsx
> 💅 add min height to polaroid

- api/package-lock.json
- api/package.json
dunno how this got screwed up again, but necessary for #213
> ⬆️ update @types/ramda _AGAIN_ 🙄

- dashboard-app/src/App.tsx
- dashboard-app/src/features/dashboard/ByActivity/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByActivity/index.tsx
- dashboard-app/src/features/dashboard/ByTime/TimeTabs.tsx
- dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/VolunteerTabs.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/features/dashboard/Dashboard/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/Dashboard/index.tsx
- dashboard-app/src/features/dashboard/components/DataTable/index.tsx
- dashboard-app/src/features/dashboard/components/DataTable/types.ts
- dashboard-app/src/features/dashboard/components/StackedBarChart/Chart.tsx
- dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx
- dashboard-app/src/features/dashboard/components/Title.tsx
- dashboard-app/src/features/dashboard/copy/titles.ts
- dashboard-app/src/features/dashboard/util.ts
- dashboard-app/src/features/navigation/__tests__/pages.test.ts
- dashboard-app/src/features/navigation/pages.ts
**Changes:**
- update titles on all pages
- create copy object
- create Title component to allow title and date to be separated
fixes #203
> 💬 update page titles and descriptions

- dashboard-app/src/features/dashboard/ByActivity/index.tsx
- dashboard-app/src/features/dashboard/ByTime/TimeTabs.tsx
- dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/VolunteerTabs.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/features/dashboard/components/DataTable/DataTableHeaderRow.tsx
- dashboard-app/src/features/dashboard/components/DataTable/__tests__/index.test.tsx
- dashboard-app/src/features/dashboard/components/DataTable/index.tsx
- dashboard-app/src/features/dashboard/components/DataTable/types.ts
- dashboard-app/src/features/dashboard/dataManipulation/__tests__/aggregatedToCsv.test.ts
- dashboard-app/src/features/dashboard/dataManipulation/aggregatedToCsv.ts
- dashboard-app/src/features/dashboard/dataManipulation/downloadCsv.ts
- dashboard-app/src/features/dashboard/hooks/useOrderable.ts
- dashboard-app/src/features/dashboard/util.ts
- lib/twine-util/index.ts
- lib/twine-util/misc.ts
~~**DO NOT MERGE**~~
Fix bad naming ~~before merging!~~ <- suggestions welcome
Related to #98
> 🐛fix csv sorting

- .travis.yml
- dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- undo test changes
- change default sort order on time table
missed in #223
> 🐛 fix default sort order of Time table

- .travis.yml
- api/package-lock.json
- api/package.json
- dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- lib/twine-util/package-lock.json
- lib/twine-util/package.json
> 🐛 fix default sort order of Time table and update ramda types

- api/bin/clone_db.ts
- dashboard-app/src/features/dashboard/Dashboard/index.tsx
- dashboard-app/src/features/dashboard/Dashboard/useDashboardStatistics.ts
- dashboard-app/src/features/dashboard/copy/titles.ts
> 🐛 remove erroneous time shift used for informal testing

- dashboard-app/src/features/dashboard/components/StackedBarChart/Legend/index.tsx
kinda relates #239
Fine to merge into gh master/hosting staging. Hotfix to be deployed to production separately.
> 💅 use native scroll on legend bar

- visitor-app/src/cb_admin/pages/VisitsData.js
fixes #241 
QA will re-test this defect on the provided review app: https://twine-visitor-pr-242.herokuapp.com/
Squash into base branch.
> 🐛 fix csv time formatting on visitor app

- docs/pull_request_template.md
- docs/workflow.md
> 📝 add docs and PR template for new release pipeline

- .heroku/create_review_app.sh
- .heroku/delete_review_app.sh
#238 
- add scripts to simplify creation and deletion of DIY review apps
N/A
Tested with review apps for PR 227
N/A 
N/A
> 📜 add review app scripts

- visitor-app/src/visitors/pages/SignIn/QrScanner.js
- fix styling on webcam element
- when merged
> 💅 fix styling on webcam element

- .heroku/create_review_app.sh
- forgot to `SHIFT` when parsing arguments
- properly reference variables 🙈
N/A
N/A
N/A
> 🐛 fix argument parsing in review app script

- .gitignore
- add `rdb` files to `.gitignore`
N/A
N/A
N/A
> 🔧 ignore redis dump files

- dashboard-app/src/features/dashboard/copy/faqs.ts
Addresses to PO comment
- add question mark to first question on FAQ page
- Look at FAQ page, verify `?` is there
- PO approved, release when merged
> 💬 PO comment: add question mark to FAQ question

- docs/pull_request_template.md
- docs/workflow.md
- remove sneaky sentence
- remove release checklist as it's covered by pipeline
- update docs to include new pipeline column
> 📝 update workflow docs and template

- dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx
- update volunteer no select copy on chart
- na
- dashboard
> 💬 graph copy change

- dashboard-app/src/features/dashboard/components/StackedBarChart/Chart.tsx
- dashboard-app/src/features/dashboard/components/StackedBarChart/Legend/LegendItem.tsx
- dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx
- dashboard-app/src/features/dashboard/components/StackedBarChart/utils/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/components/StackedBarChart/utils/util.ts
- change select/deselect order
- add transition on selection
- tidy up isVisible logic
- press "All" and expect all volunteers to be selected
- press again and expect all volunteers to be deselected
- select 1 volunteer
- press "All" and expect all volunteers to be selected
- when merged 
- dashboard app
> 💅 improve legend functionality

- api/config/config.production.ts
- api/config/config.testing.ts
- fix default redis address in all envs
- na
> 🔧 fix default redis address in all envs

- dashboard-app/src/features/dashboard/copy/faqs.ts
fixes #284 
- add contact question to FAQ section
- check new copy on FAQ page
- Release = minor (Devs can release)
- Dashboard
> 💬 add new FAQ copy

- dashboard-app/src/App.tsx
- dashboard-app/src/features/dashboard/ByActivity/index.tsx
- dashboard-app/src/features/dashboard/ByTime/TimeTabs.tsx
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/VolunteerTabs.tsx
- dashboard-app/src/features/dashboard/ByVolunteer/index.tsx
- dashboard-app/src/features/dashboard/components/StackedBarChart/index.tsx
- dashboard-app/src/features/dashboard/components/Toggle.tsx
- dashboard-app/src/features/dashboard/components/UnitToggle.tsx
- dashboard-app/src/features/dashboard/components/UtilityBar.tsx
relates #183 
- use context for app wide state for unit
- update toggle and util bar to support this
- add default value not to break tests
- change unit on time page
- observe new unit persistent on all pages
- na - release when ready
- dashboard
> ♻️ context demo

- api/package-lock.json
- api/package.json
- api/src/api/v1/community_businesses/__tests__/volunteer_logs.test.integration.ts
- api/src/api/v1/community_businesses/volunteer_logs.ts
- api/src/models/community_business.ts
- api/tslint.json
- lib/tslint-config-twine/index.js
- volunteer-app/www/css/ionic.app.css
- volunteer-app/www/js/controllers/edit-log-controller.js
- volunteer-app/www/js/controllers/edit-project-controller.js
- volunteer-app/www/js/controllers/profile-controller.js
- volunteer-app/www/js/controllers/settings-controller.js
- volunteer-app/www/js/services/api-service.js
- volunteer-app/www/templates/profile.html
- volunteer-app/www/templates/register.html
related to #298 
fixes #300 
fixes #297 
Addresses review comments
- Move "you haven't added any logs" message 
- Fix datepicker limits for admins
- Change "error" popup to "alert"
- Add postcode field to profile page
- Hide loading spinner when error occurs on editing project name
- Try to edit previous months log, check that datepicker defaults to date of log and can choose arbitrary date
- Check can update/edit postcode on profile page
- Edit project: try a duplicate name, observe that spinner eventually disappears
- N/A to be re-checked by PO in #298
- Volunteer app
> 🐛 address review comments on volunteer app

- volunteer-app/www/js/controllers/new-log-controller.js
fixes #313
- Store processed payload data in offline cache instead of unprocessed form data
- With network disabled, attempt to create a log for multiple users at the same time
- When saving fails, enable network and attempt to sync
- Syncing should succeed
- Bundle with #298 
- Volunteer app
> 🐛 fix processing when trying to sync multiple logs stored offline

- dashboard-app/src/features/dashboard/ByActivity/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByTime/__tests__/index.test.ts
- dashboard-app/src/features/dashboard/ByVolunteer/__tests__/index.test.ts
- visitor-app/src/cb_admin/pages/__tests__/Activities.test.js
- visitor-app/src/cb_admin/pages/__tests__/AnonUser.test.js
- visitor-app/src/cb_admin/pages/__tests__/ConfirmPassword.test.js
- visitor-app/src/cb_admin/pages/__tests__/Dashboard.test.js
- visitor-app/src/cb_admin/pages/__tests__/Feedback.test.js
- visitor-app/src/cb_admin/pages/__tests__/ForgotPassword.test.js
- visitor-app/src/cb_admin/pages/__tests__/Login.test.js
- visitor-app/src/cb_admin/pages/__tests__/ResetPassword.test.js
- visitor-app/src/cb_admin/pages/__tests__/Settings.test.js
- visitor-app/src/cb_admin/pages/__tests__/Visitor.test.js
- visitor-app/src/cb_admin/pages/__tests__/VisitorDetails.test.js
- visitor-app/src/visitors/pages/__tests__/Login.test.js
- visitor-app/src/visitors/pages/__tests__/Signup.test.js
- visitor-app/src/visitors/pages/__tests__/homeVisitor.test.js
fixes TwinePlatform/twine-visitor#647
- Update `fireEvent` usage in visitor app testing
- Prefer `toHaveTextContent` matcher
- Minor formatting
N/A (only changes to test code)
N/A
N/A
> ♻️ update usage of fireEvent API

- api/src/api/v1/community_businesses/__tests__/volunteer_logs.test.integration.ts
- api/src/api/v1/community_businesses/volunteer_logs.ts
- api/src/api/v1/types.ts
- api/src/auth/scopes/index.ts
- api/src/models/types.ts
- api/src/models/volunteer_log.ts
- api/src/types/internal.ts
fixes #295 
- Add `Unpack<T>` type
- Add syncLogs method to VolunteerLogs model
- Transform payload into VolunteerLog[] in handler
- Move role checks into syncLogs
- Move permissions checks into syncLogs
- Same requirements as in #259 
N/A
N/A
> ♻️ refactor volunteer-logs sync handler

- api/docs/public_api.md
- docs/README.md
- fixes broken links
- fixes public API spec
N/A
N/A 
N/A
> 📝 fix links in documentation

- visitor-app/src/visitors/pages/SignUp/SignUpForm/SideCopy.js
- visitor-app/src/visitors/pages/SignUp/SignUpForm/index.js
fixes #305
- Remove SMS contact consent checkbox
- Minor formatting
- Check can still sign up as new visitor
- Wait for PO confirmation
- Visitor app
> 💬 remove sms-checkbox and minor formatting

- .travis.yml
- .travis/cc-report.sh
- remove lerna from travis
- remove jobs as we only run 1
- run coverage always (as running CI on branch only rather than branch+PR)
🤷🏽‍♀️ no faster though
- na
- na
- na
> 👷🏻‍♀️ Travis configuration

- api/bin/clone_db.ts
Prevents unnecessary failures
- add --if-exists flag to restore command
N/A
N/A 
N/A
> 🐛 add --if-exists flag to pg_restore command

- api/src/api/v1/types/api.ts
- api/src/models/types.ts
fixes ...master 😬
- Define visit sign in types
- Does it build?
- N/A
- N/A
> 🚑 fix type issue

- .travis.yml
- api/config/__tests__/index.test.ts
related #344 
- add nativeApp matrix for trav
- fix failing api config test
- check tests are running for nativeApp on trav
> 👷🏻‍♀️ add nativeApp matrix for trav

- nativeApp/package.json
- nativeApp/src/lib/ui/AddBar.tsx
- nativeApp/src/lib/ui/Page.tsx
- nativeApp/src/lib/ui/Tabs.tsx
- nativeApp/src/lib/ui/TimeCard/index.tsx
- nativeApp/src/lib/ui/modals/ConfirmationModal.tsx
- nativeApp/src/lib/ui/typography.tsx
- nativeApp/src/screens/admin_views/AdminTime/AdminTimePage/index.tsx
- nativeApp/src/screens/admin_views/Projects/ProjectCard.tsx
- nativeApp/src/screens/admin_views/Projects/index.tsx
- nativeApp/src/screens/admin_views/Volunteers/AddVolunteer/index.tsx
- nativeApp/src/screens/admin_views/Volunteers/VolunteersPage/VolunteerCard.tsx
- nativeApp/src/screens/admin_views/Volunteers/VolunteersPage/index.tsx
relates #338 
- add confirmation modal to delete/archive/restore buttons
- add page to add new volunteer
> 💅 hopefully final UI changes

- visitor-app/src/cb_admin/pages/VisitsData/AgeGroupChart.js
- visitor-app/src/cb_admin/pages/VisitsData/CsvExportButton.js
- visitor-app/src/cb_admin/pages/VisitsData/GenderChart.js
- visitor-app/src/cb_admin/pages/VisitsData/HorizontalDrillDownChart.js
- visitor-app/src/cb_admin/pages/VisitsData/TimePeriodChart.js
- Add components for each chart on visits page
- Extract CSV export functionality
- Add drill-down chart component
N/A (manual testing will be together with subsequent PRs)
N/A
N/A
> 📊 Extract chart components

- visitor-app/src/cb_admin/components/Tabs/Tab.js
- visitor-app/src/cb_admin/components/Tabs/TabGroup.js
- visitor-app/src/cb_admin/components/Tabs/TabList.js
- visitor-app/src/cb_admin/components/Tabs/TabListItem.js
- visitor-app/src/cb_admin/components/Tabs/index.js
- visitor-app/src/cb_admin/pages/VisitsData/Toggle.js
- Add tabs components (basically the same as in the dashboard app)
- Add toggle component (also same as in dashboard app)
N/A to be tested manually with later PRs
N/A
N/A
> ✨ add tabs components

- dashboard-app/src/App.tsx
- dashboard-app/src/features/dashboard/ByActivity/datePickerConstraints.ts
- dashboard-app/src/features/dashboard/ByProject/ProjectTabs.tsx
- dashboard-app/src/features/dashboard/ByProject/datePickerConstraints.ts
- dashboard-app/src/features/dashboard/ByProject/index.tsx
- dashboard-app/src/features/dashboard/ByProject/useAggregateDataByProject.ts
- dashboard-app/src/features/dashboard/ByTime/datePickerConstraints.ts
- dashboard-app/src/features/dashboard/ByVolunteer/datePickerConstraints.ts
- dashboard-app/src/features/dashboard/Dashboard/index.tsx
- dashboard-app/src/features/dashboard/dataManipulation/tableType.ts
- dashboard-app/src/features/navigation/Navbar/index.tsx
- dashboard-app/src/features/navigation/__tests__/pages.test.ts
- dashboard-app/src/features/navigation/pages.ts
- dashboard-app/src/lib/api/index.ts
related to #335 
- Add projects page
- Update navigation
- NOTE: This **doesn't** include the toggle between projects -> activities which is coming in a subsequent PR
- Check navbar displays new working link to `/projects`
- Check dashboard displays new working link to `/projects`
- Check graph renders accurately on `/projects`
- Check table renders accurately on `/projects`
- Check legend works
- Check filters/toggles work
- Check CSV download works and re-creates table in CSV form
- Not yet.
- N/A
> ✨ Add projects page to dashboard

- visitor-app/src/cb_admin/pages/VisitsData/__tests__/data.test.js
- visitor-app/src/cb_admin/pages/VisitsData/__tests__/dateRange.test.js
- visitor-app/src/cb_admin/pages/VisitsData/__tests__/util.test.js
- visitor-app/src/cb_admin/pages/VisitsData/data.js
- visitor-app/src/cb_admin/pages/VisitsData/dateRange.js
- visitor-app/src/cb_admin/pages/VisitsData/index.js
- visitor-app/src/cb_admin/pages/VisitsData/util.js
- visitor-app/src/shared/style_guide.js
**DO NOT MERGE**
**MERGE #382 FIRST**
fixes #394 
fixes #395 
- Assign fixed colours to chart gender and age categories
- Capitalise genders
- Move reasons for visiting chart to bottom
- Add bottom spacing
- Use colour palette from design system on doughnut charts to accommodate more than 3 categories
- Ensure colours for each category remain consistent when changing filter values
- Ensure genders are consistently capitalised
- PO approval, release with feature branch
- Visitor app
> 🚸 improve UI/UX on visit charts page

- api/src/api/v1/community_businesses/__tests__/volunteer_logs.test.integration.ts
fixes #423
- remove hard coded date and replace with dynamically generated date
- n/a change in tests not production code
- n/a
- n/a
> 🐛 fix synced logs failing test

- api/package.json
- dashboard-app/package.json
- temp-admin-dashboard-app/package.json
- visitor-app/package.json
fixes broken deployment
- set node version
- api
- visitor
- dashboard
> ⬆️  set npm version to fix prune deployment bug

- api/src/api/v1/community_businesses/__tests__/visit_activities.test.integration.ts
- api/src/models/__tests__/community_business.test.integration.ts
- api/src/models/community_business.ts
- visitor-app/src/api/index.js
- visitor-app/src/cb_admin/pages/Activities/ActivityLabel.js
- visitor-app/src/cb_admin/pages/Activities/ActivityTable.js
- visitor-app/src/cb_admin/pages/Activities/CategorySelect.js
- visitor-app/src/cb_admin/pages/Activities/__tests__/index.test.js
- visitor-app/src/cb_admin/pages/Activities/index.js
- visitor-app/src/shared/components/form/LabelledSelect.js
fixes #385 
- Add select box to activities table to allow changing category
- Display activities sorted by ID
- Move Activity page related components into own directory
- Add "Saving" beat loader on all write events
- Add new visit activity
- Check newly added activity has correct category
- Update category of existing activity
- Delete activity
- Loading spinner should be visible on page even in scrolled down
- PO approval
- Visitor app
> ✨ manage visit categories w/ select

- nativeApp/src/Router.tsx
- nativeApp/src/screens/settings_views/SettingsPage/index.tsx
- nativeApp/src/screens/settings_views/TnC/index.tsx
- nativeApp/src/screens/views_content/TnC.tsx
Changes
- added TnC page to the setting
> setup TnC page

- nativeApp/src/screens/open_views/Register/index.tsx
> Ogrnisation Registration

- api/package-lock.json
- api/package.json
fixes ...
- updated hapi.pino to a non-breaking version in the api
-
- 
- 
- 
-
> updated pino to latest version

- nativeApp/src/api/index.ts
- nativeApp/src/lib/ui/forms/Dropdown.tsx
- nativeApp/src/lib/ui/forms/InputWithInlineLabel.tsx
- nativeApp/src/lib/ui/forms/UserForm/index.tsx
- nativeApp/src/screens/settings_views/Profile/index.tsx
> populate and enable profile update

- dashboard-app/src/features/dashboard/components/DataTable/LogsDataTableRow.tsx
- dashboard-app/src/lib/ui/index.css
fixes ...
View Log button
-  Added purple background.
-  Added rounded corners.
-  Added  white text col.or.
- Removed the border.
- 
- 
- 
-
> Dashboard logs tab

- dashboard-app/src/features/dashboard/ByProject/index.tsx
> extrabuttonsvisible

- nativeApp/package.json
- nativeApp/src/lib/ui/HoursAndMinutesText.tsx
> fix container

- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/src/api/index.ts
- nativeApp/src/lib/ui/AddNote.tsx
- nativeApp/src/lib/ui/forms/DateTimePicker/index.tsx
- nativeApp/src/lib/ui/forms/Dropdown.tsx
- nativeApp/src/lib/ui/forms/FuzzySearchBox.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/screens/admin_views/AddTime/index.tsx
- nativeApp/src/screens/open_views/Login/index.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
fixed registration fuzzy search
> Fuzzy search i os

- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
remove endTime, go back to setting duration directly
> revert to duration

- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
fixed a few bugs with add another on time form
> set admin only, and bug on removing them

- dashboard-app/public/downloads/upload_data_template.csv
- dashboard-app/src/features/dashboard/ByUploadData/index.tsx
- dashboard-app/src/lib/api/index.ts
> Dashboard upload screen

- api/database/migrations/20201002_add_region.sql
- api/database/migrations/20201002_add_region.ts
- api/database/migrations/sql/20201002_add_region.sql
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/lib/ui/modals/logout.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
fixes #550 #554 #553 
- logout modal styling
> Development issues

- api/src/api/v1/community_businesses/register.ts
- api/src/models/community_business.ts
- api/src/models/types.ts
- api/src/services/email/index.ts
- nativeApp/app.json
backend changes required for the admin code to be sent together with the email. Deployed in heroku
> fix admin code bug

- nativeApp/src/lib/ui/forms/DateTimePicker/index.tsx
- nativeApp/src/lib/ui/forms/FuzzySearchBox.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/screens/admin_views/Time/TimePage/index.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
> adjust time form

- nativeApp/src/screens/open_views/Register/index.tsx
> fix spaces on reg form

- nativeApp/src/screens/volunteer_views/VolunteerHome/index.tsx
> add refresh badges

- api/database/migrations/20201014_add_notes.sql
- api/database/migrations/20201014_add_notes.ts
- api/database/migrations/20201014_add_pushnotification.sql
- api/database/migrations/20201014_add_pushnotification.ts
- api/database/migrations/20201014_create_badges_table_view.sql
- api/database/migrations/20201014_create_badges_table_view.ts
- api/database/migrations/sql/20201014_add_notes.sql
- api/database/migrations/sql/20201014_add_pushnotification.sql
- api/database/migrations/sql/20201014_create_badges_table_view.sql
- nativeApp/app.json
> add migration of badges,notes and pushnotifs

- dashboard-app/src/lib/ui/components/LogCreateModal.tsx
- dashboard-app/src/lib/ui/components/LogViewModal.tsx
- dashboard-app/src/lib/ui/index.css
> Style log creation modal

- dashboard-app/src/lib/ui/components/LogEditModal.tsx
- dashboard-app/src/lib/ui/components/NoteModal.tsx
- dashboard-app/src/lib/ui/components/ProjectModal.tsx
> Style log edit modal

- dashboard-app/src/lib/api/index.ts
- dashboard-app/src/lib/ui/components/InviteModal.tsx
- dashboard-app/src/lib/ui/index.css
> Dsahboard email invite

- nativeApp/app.json
- nativeApp/src/screens/admin_views/Time/EditTime/index.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
- nativeApp/src/screens/volunteer_views/Time/EditTime/index.tsx
> readd redux on edittime page for project and activity

- api/src/api/v1/community_businesses/volunteer_logs.ts
- api/src/models/types.ts
- nativeApp/src/lib/ui/TimeCard/index.tsx
- nativeApp/src/lib/ui/forms/DropdownTime.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/lib/ui/modals/NoteModal.tsx
- nativeApp/src/redux/entities/logs.ts
- nativeApp/src/screens/admin_views/Time/EditTime/index.tsx
- nativeApp/src/screens/admin_views/Time/TimePage/index.tsx
- nativeApp/src/screens/volunteer_views/Time/EditTime/index.tsx
- nativeApp/src/screens/volunteer_views/Time/index.tsx
> fix edit logs, adjust access cope of volunteer logs line 190

- nativeApp/src/lib/ui/SearchBar.tsx
- nativeApp/src/screens/admin_views/Volunteers/VolunteersPage/index.tsx
> add searchbar component, add to volunteers page

- nativeApp/app.json
> changed android value for keyboard layoutmode

- api/src/api/v1/community_businesses/register.ts
- nativeApp/src/screens/open_views/Register/index.tsx
> fixes #607

- api/src/api/v1/community_businesses/badges.ts
- api/src/models/badges.ts
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/redux/entities/logs.ts
- nativeApp/src/screens/admin_views/AddTime/index.tsx
- nativeApp/src/screens/volunteer_views/AddTime/index.tsx
> fixed #610 badges endpoint app crash

- nativeApp/src/lib/ui/forms/DatePicker.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
> switch to date picker

- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/screens/volunteer_views/AddTime/index.tsx
> return volunteers to home on submit logs

- nativeApp/src/authentication/types.ts
- nativeApp/src/screens/open_views/Login/index.tsx
> add new async and intial effect in loading screen

- nativeApp/src/lib/ui/Page.tsx
- nativeApp/src/lib/ui/modals/NoteModal.tsx
> added keyboardShouldPersistTaps={'handled'} to Page and NoteModal component

- nativeApp/src/lib/ui/AddNote.tsx
- nativeApp/src/lib/ui/modals/NoteModal.tsx
> add a limit and a characters left label

- nativeApp/src/screens/admin_views/Projects/ProjectCard.tsx
- nativeApp/src/screens/settings_views/SettingsPage/index.tsx
> Confirm modal reminders

- nativeApp/src/lib/ui/forms/DatePicker.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
> pass usertype to datepicker, adjust date picker

- nativeApp/src/lib/ui/forms/DatePicker.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
> issue was start time wasn't resetting, adjusted that

- nativeApp/src/lib/ui/forms/InputWithIcon.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/screens/open_views/Login/index.tsx
> add an "onFocus" that removes the logo

- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
> resolved bug that was blocking error modal for wrong duration

- nativeApp/src/screens/admin_views/Time/TimePage/index.tsx
- nativeApp/src/screens/volunteer_views/Time/index.tsx
> Just 50 logs

- nativeApp/src/lib/ui/Invite.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/lib/ui/modals/InvitationModal.tsx
- nativeApp/src/screens/admin_views/Time/TimePage/index.tsx
- nativeApp/src/screens/volunteer_views/Time/index.tsx
- nativeApp/src/screens/volunteer_views/VolunteerHome/index.tsx
> reconnected the selector up on time page

- dashboard-app/src/features/dashboard/ByLog/useAggregateDataByLog.ts
- dashboard-app/src/features/dashboard/components/DataTable/LogsDataTableRow.tsx
- dashboard-app/src/lib/ui/components/LogCreateModal.tsx
- dashboard-app/src/lib/ui/components/LogEditModal.tsx
- dashboard-app/src/lib/ui/components/LogViewModal.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
> Dsahboard switch to date from datetime

- nativeApp/src/lib/ui/modals/NoteModal.tsx
> added keyboard avoiding view

- nativeApp/src/lib/ui/modals/NoteModal.tsx
- nativeApp/src/screens/open_views/Register/index.tsx
> Reg form errors

- nativeApp/src/screens/admin_views/Volunteers/VolunteersPage/index.tsx
> fixed the filter bug

- nativeApp/src/screens/admin_views/Time/TimePage/index.tsx
- nativeApp/src/screens/volunteer_views/Time/index.tsx
> reworked confirm modal, match admin time page to volunteer

- nativeApp/src/lib/ui/modals/NoteModal.tsx
> Note modal

- api/src/api/v1/community_businesses/volunteers/get.ts
- api/src/models/types.ts
- api/src/models/volunteer.ts
- nativeApp/app.json
- nativeApp/src/api/index.ts
- nativeApp/src/lib/ui/CardWithButtons/NotificationButton.tsx
- nativeApp/src/screens/admin_views/Projects/ProjectCard.tsx
i have created new endpoint for the push notification reminder for volunteers that hasn't log for the past 7 days. When the box is check it will trigger the call to that api.
> Pushnotifs checkbox

- dashboard-app/src/features/dashboard/ByActivity/index.tsx
- dashboard-app/src/features/dashboard/ByLog/index.tsx
- dashboard-app/src/features/dashboard/ByLog/useAggregateDataByLog.ts
- dashboard-app/src/features/dashboard/ByTime/index.tsx
- dashboard-app/src/features/dashboard/ByUploadData/index.tsx
- dashboard-app/src/features/dashboard/ByUser/index.tsx
- dashboard-app/src/features/dashboard/ByUser/useAggregateDataByUser.ts
- dashboard-app/src/features/dashboard/components/CategoryPicker.tsx
- dashboard-app/src/features/dashboard/components/DataTable/LogsDataTable.tsx
- dashboard-app/src/features/dashboard/components/DataTable/LogsDataTableRow.tsx
- dashboard-app/src/features/dashboard/components/DataTable/ProjectsDataTable.tsx
- dashboard-app/src/features/dashboard/components/DataTable/UsersDataTable.tsx
- dashboard-app/src/features/dashboard/components/SearchPicker.tsx
- dashboard-app/src/features/dashboard/dataManipulation/aggregatedToCsvLogs.ts
- dashboard-app/src/features/dashboard/dataManipulation/aggregatedToTableDataLogs.ts
- dashboard-app/src/features/dashboard/dataManipulation/downloadCsvLogs.ts
- dashboard-app/src/lib/api/index.ts
- dashboard-app/src/lib/hooks/useOutsideAlerter.ts
- dashboard-app/src/lib/ui/components/DeleteModal.tsx
- dashboard-app/src/lib/ui/components/InviteModal.tsx
- dashboard-app/src/lib/ui/components/LogCreateModal.tsx
- dashboard-app/src/lib/ui/components/LogEditModal.tsx
- dashboard-app/src/lib/ui/components/LogViewModal.tsx
- dashboard-app/src/lib/ui/components/NoteModal.tsx
> fixed warnings

- nativeApp/package-lock.json
- nativeApp/package.json
- nativeApp/src/api/index.ts
- nativeApp/src/lib/ui/HelpSlides/last.tsx
- nativeApp/src/lib/ui/forms/TimeForm/index.tsx
- nativeApp/src/lib/utils/cache.ts
- nativeApp/src/screens/admin_views/Home/index.tsx
- nativeApp/src/screens/open_views/Login/index.tsx
- nativeApp/src/screens/settings_views/SettingsPage/index.tsx
- nativeApp/src/screens/volunteer_views/VolunteerHome/index.tsx
> time form refactor

- dashboard-app/src/features/auth/pages/Login/index.tsx
- dashboard-app/src/lib/ui/components/SupportModal.tsx
- dashboard-app/src/lib/ui/design_system/spacing.ts
> Tm682 dashboard support modal

- dashboard-app/src/features/auth/pages/Login/index.tsx
> Update link to registration page

- dashboard-app/src/features/auth/pages/Login/index.tsx
> remove forward slash after url

- dashboard-app/public/index.html
- visitor-app/public/index.html
fixes ...
Add umami analytics script to volunteer dashboard and visitor webapp
Check umami to see the data
- 
-
> Add Umami to Webapps
